baseURL = "https://blog.acoustid.org/"
languageCode = "en-us"
title = "AcoustID News and Updates"
theme = "mini"

[params]
  avatarLink = "https://blog.acoustid.org/"
  copyright = " "
  enableComments = true
