baseURL = "https://blog.acoustid.org/"
languageCode = "en-us"
title = "AcoustID News and Updates"
theme = "mini"

[params]
  avatarLink = "https://blog.acoustid.org/"
  copyright = " "
  facebookPixelID = "1567565503441970"
  enableFacebookPixel = true
  enableFacebookSDK = true
  enableFacebookComments = true

[social]
  facebook = "https://www.facebook.com/acoustid"
  twitter = "https://twitter.com/acoustid"
  github = "https://github.com/acoustid"
